### ISSUE TITLE
请问大佬想要学习这门课程，完成这个实验，需要那些资料？

### ISSUE THREAD

**Issue by Sherlockouo** [qdslovelife/bustub#1]
求大佬指点 除了lru会写一点 后面的实验感觉 很难下手。

**Comment by qdslovelife** [comment]
我个人觉得课程视频已经讲得很清楚了，你也可以看看课程提到的那本教材。
做实验的话，最好的方法就是自己写单元测试，一个功能接一个的去实现，这样你的思路会比较集中。

**Comment by Sherlockouo** [comment]
嗷 谢谢大佬 还没看视频 哈哈。单看实验指导 确实让我有些头疼
