### ISSUE TITLE
cmake问题

### ISSUE THREAD

**Issue by ZhanGHanG9991** [qdslovelife/bustub#2]
你好 我在cmake过程中遇到了这个问题，说是找不到GTest的配置文件，大佬有遇到过吗？
![image](https://user-images.githubusercontent.com/34939716/149626912-62797390-094c-43c1-bc0f-c3a7b0098bcf.png)

**Comment by qdslovelife** [comment]
如果你执行了`./vcpkg/vcpkg install gtest`还是出错的话，那么可能就是gtest的版本不对。你可以在[vcpkg官网](https://vcpkg.io/en/packages.html)搜索然后选择正确的gtest版本。不过这个问题我只在windows上遇见过。

**Comment by ZhanGHanG9991** [comment]
没找到vcpkg，大佬说的是哪个，这里只有一个文件夹
![image](https://user-images.githubusercontent.com/34939716/149687281-630386b5-9f66-45ad-bb0d-aa48d5f5efb5.png)

**Comment by qdslovelife** [comment]
将vcpkg克隆到你的项目之后，需要先执行对应的脚本。Unix系统是bootstrap-vcpkg.sh，之后你才能使用vcpkg安装包。更具体的使用过程你可以参考[Vcpkg: 总览](https://github.com/microsoft/vcpkg/blob/master/README_zh_CN.md)。

**Comment by ZhanGHanG9991** [comment]
好的 非常感谢！ 我来试下
