### ISSUE TITLE
请问下图片中的分数是什么意思？是满分吗？

### ISSUE THREAD

**Issue by ZhanGHanG9991** [qdslovelife/bustub#3]
![image](https://user-images.githubusercontent.com/34939716/152338194-cdd4066a-33b3-472d-ab0e-43be1078c36d.png)

**Comment by qdslovelife** [comment]
这门课有一个自动测评系统，可以检测你的代码的正确性和性能。具体内容你可以参考[FAQ](https://15445.courses.cs.cmu.edu/fall2021/faq.html#q7)。

**Comment by ZhanGHanG9991** [comment]
好的 非常感谢！！！
