### ISSUE TITLE
lab2 GetLocalHighBit()

### ISSUE THREAD

**Issue by ZhanGHanG9991** [qdslovelife/bustub#5]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/34939716/157470570-d3f7018f-8830-46e8-ba65-9385a5e0ecb0.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/34939716/157471454-e828c8db-f801-48cf-9fbd-2a4a68ebd770.png">

请问，我看GetGlobalDepthMask以及GetLocalDepthMask都是为了求低几位的bit值从而使得低几位的bit值为1，然后去和Hash(key)进行&运算，为什么这个GetLocalHighBit是在求高位的bit值？这个GetLocalHighBit函数是什么意思呢？没有看明白。

**Comment by qdslovelife** [comment]
这个函数用于辅助计算split image index，你需要结合下面这个函数一起去理解：
https://github.com/qdslovelife/bustub/blob/6148a493d27c31894fd7d89e19556329c7d919ab/src/storage/page/hash_table_directory_page.cpp#L72
我用索引3、局部深度为2举两个例子：

1. 索引3指向的哈希桶溢出，局部深度增加为3，调用GetLocalHighBit()返回100B，经过GetSplitImageIndex()内部的位运算后得到111B，即索引7。
2. 索引3指向的哈希桶为空，在合并桶的时候我们最后再降低局部深度，所以局部深度仍为2，调用GetLocalHighBit()返回100B，经过GetSplitImageIndex()内部的位运算后得到01B，即索引1。

这个函数实际上就是将bucket_idx在局部深度下的最高位由0变为1或由1变为0。

**Comment by ZhanGHanG9991** [comment]
你好啊 我看懂了这两个函数，非常感谢！
<img width="822" alt="image" src="https://user-images.githubusercontent.com/34939716/157578402-e505cd90-b603-4685-80d7-6cf91bdd3c36.png">
如果按图上所说，为什么不能直接写成，将索引的局部深度下的最高位反转呢？你的方法实现我没有看懂，我的想法就是可能判断一下索引的局部深度下的最高位是0还是1，直接设定这一位为1或者0？

**Comment by qdslovelife** [comment]
你的方法也是可行的。至于我为什么写的这么晦涩，我只能说我也不记得了:sweat_smile:。

**Comment by ZhanGHanG9991** [comment]
好的 谢谢！

**Comment by 2w1nd** [comment]
问以下，GetSplitImageIndex的作用是获得分割后的bucket局部深度深度的最高位对吧？可为什么要这么去写呢，没看明白
![image](https://user-images.githubusercontent.com/64266855/160971139-d7de87fb-9557-47cf-bf22-506a68439798.png)

**Comment by qdslovelife** [comment]
这个地方我的注释和命名确实有问题。实际上，GetLocalHighBit()的执行过程是把一个bucket_idx的局部深度的最高位反转，也就是0变成1或1变成0，然后把低位都置0。
https://github.com/qdslovelife/bustub/blob/6148a493d27c31894fd7d89e19556329c7d919ab/src/storage/page/hash_table_directory_page.cpp#L74
上面这行代码再将GetLocalHighBit()返回的值与原bucket_idx的低位（也就是不包括局部深度的最高位）做一个或运算。最后与掩码做与运算就可以返回它的配对桶的索引了。

**Comment by 2w1nd** [comment]
嗯，大致算法我明白，但这么做的原因是什么？这样可以让bucket分布的更加均匀么？

**Comment by 2w1nd** [comment]
好的了解了，感谢回复
