### ISSUE TITLE
splitInsert rehash

### ISSUE THREAD

**Issue by ZhanGHanG9991** [qdslovelife/bustub#6]
https://github.com/qdslovelife/bustub/blob/df9c28b67abf2e6553354823f8af2122b645141a/src/container/hash/extendible_hash_table.cpp#L178
你好，对于这个rehash操作我有些疑问。您的代码中写的是从num_read = 0开始，直到num_read == num_readable结束。我有疑问的是bucket中的数据应该不是按序存放的？我们不能简单的将num_read作为索引，因为如果bucket中间某个位置曾经被remove过，这个索引位置的readable就是0，就会陷入死循环？我想是不是应该将索引的index和num_read分开，见如下代码。
<img width="862" alt="image" src="https://user-images.githubusercontent.com/34939716/157777821-170e48cd-a2c0-414a-96e4-a21413944a39.png">

**Comment by qdslovelife** [comment]
这段代码的真正问题是这行if是多余的：https://github.com/qdslovelife/bustub/blob/6148a493d27c31894fd7d89e19556329c7d919ab/src/container/hash/extendible_hash_table.cpp#L182
因为rehash只会发生在桶将要溢出时，所以桶内的每一个slot都是可读的。在循环内唯一要做的就是判断是否要将某个键值对移动到配对桶中。

**Comment by ZhanGHanG9991** [comment]
噢噢噢确实，非常感谢！
