### ISSUE TITLE
join得到的元组的RID怎么赋值？

### ISSUE THREAD

**Issue by ZhanGHanG9991** [qdslovelife/bustub#7]
https://github.com/qdslovelife/bustub/blob/6148a493d27c31894fd7d89e19556329c7d919ab/src/execution/nested_loop_join_executor.cpp#L78
你好，请问下，join后的元组，这里的RID为什么被赋值为左边tuple的RID？
还是说其实这里并没有必要赋值RID，因为只是select，得到的这个表并没有落盘到数据库中，不需要RID？

**Comment by qdslovelife** [comment]
这行代码确实是错的，但是因为`rid`在后面的代码中没有用到，所以单测没测试出来，课程提供的测试用例也没有。

**Comment by ZhanGHanG9991** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/34939716/159120892-1a2268fe-8f3c-4d1c-b44c-a560f96c5014.png">
根据RID的定义，是不是元组的物理地址？因为select语句只是读取，不需要存储这些join后的元组，所以没有RID的必要？

**Comment by qdslovelife** [comment]
对的。这个rid实际上只在insert、delete、update这三个executor中用到，因为它们可能要更新索引。

**Comment by ZhanGHanG9991** [comment]
明白了 非常感谢！！
